name: df_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  dart_frog: ^1.1.0
  equatable: ^2.0.8
  firedart: ^0.9.8
  json_annotation: ^4.9.0
  meta: ^1.18.0
  mongo_dart: ^0.10.5


dev_dependencies:
  build_runner: ^2.10.5
  dart_frog_lint: ^0.1.0
  json_serializable: ^6.11.4
  mocktail: ^1.0.3
  test: ^1.25.5
